import {
    Shield,
    Phone,
    Mail,
    BookOpen,
    BarChart3,
    Settings,
    TrendingUp,
    MessageSquare,
    HeadphonesIcon,
    ArrowLeft,
    Lock,
    CheckCircle
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export function PrivacyPolicy() {
    const navigate = useNavigate();

    const infoCollected = [
        {
            icon: <Phone className="w-5 h-5" />,
            title: "Contact Information",
            items: ["Mobile Number: +91 7400121111", "Email: sheetal@profsheetalkunderacademy.com"]
        },
        {
            icon: <BookOpen className="w-5 h-5" />,
            title: "Academic Data",
            items: ["The specific NISM Exam Series you are appearing for"]
        },
        {
            icon: <BarChart3 className="w-5 h-5" />,
            title: "Performance Data",
            items: ["Your answers to practice questions", "Formula quiz results", "Final reports generated by the system"]
        }
    ];

    const howWeUse = [
        {
            icon: <Settings className="w-5 h-5" />,
            text: "To provide, operate, and maintain our practice platform."
        },
        {
            icon: <TrendingUp className="w-5 h-5" />,
            text: "To analyse your progress and generate performance reports."
        },
        {
            icon: <MessageSquare className="w-5 h-5" />,
            text: "To improve the user experience based on your feedback."
        },
        {
            icon: <HeadphonesIcon className="w-5 h-5" />,
            text: "To communicate with you regarding updates or technical support."
        }
    ];

    return (
        <div className="min-h-screen bg-transparent">

            <div className="max-w-4xl mx-auto px-4 py-12">
                {/* Back Button */}
                <button
                    onClick={() => navigate(-1)}
                    className="flex items-center gap-2 text-gray-600 dark:text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition-colors mb-8 group"
                >
                    <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
                    <span>Back</span>
                </button>

                {/* Header */}
                <div className="text-center mb-12">
                    <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-2xl mb-6 shadow-lg shadow-emerald-500/25">
                        <Lock className="w-8 h-8 text-white" />
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4">
                        Privacy Policy
                    </h1>
                    <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto">
                        At Prof. Sheetal Kunder Academy (<a href="https://nismsmartprep.in/" className="text-blue-600 dark:text-blue-400 hover:underline" target="_blank" rel="noopener noreferrer">nismsmartprep.in</a>), one of our main priorities is the privacy of our visitors.
                    </p>
                </div>

                {/* Introduction */}
                <div className="bg-emerald-50 dark:bg-black border border-emerald-200 dark:border-gray-800 rounded-xl p-6 mb-10">
                    <div className="flex items-start gap-3">
                        <Shield className="w-6 h-6 text-emerald-600 dark:text-emerald-400 flex-shrink-0 mt-0.5" />
                        <p className="text-emerald-800 dark:text-emerald-300">
                            This Privacy Policy outlines the types of information NISMSmartPrep collects and records, and how we use it.
                        </p>
                    </div>
                </div>

                {/* Information We Collect */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                        Information We Collect
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-6">
                        By using our platform, you provide your explicit consent for us to collect and process the following:
                    </p>

                    <div className="grid md:grid-cols-3 gap-4">
                        {infoCollected.map((item, index) => (
                            <div
                                key={index}
                                className="bg-gray-50 dark:bg-black rounded-xl p-5 border border-gray-200 dark:border-gray-800 hover:border-emerald-500/50 dark:hover:border-emerald-500/50 transition-all duration-300 hover:shadow-lg"
                            >
                                <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center text-white mb-4">
                                    {item.icon}
                                </div>
                                <h3 className="font-semibold text-gray-900 dark:text-white mb-3">
                                    {item.title}
                                </h3>
                                <ul className="space-y-2">
                                    {item.items.map((text, i) => (
                                        <li key={i} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                                            <CheckCircle className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                                            <span>{text}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </div>
                </div>

                {/* How We Use Your Information */}
                <div className="mb-10">
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                        How We Use Your Information
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-6">
                        We use the information we collect in the following ways:
                    </p>

                    <div className="space-y-3">
                        {howWeUse.map((item, index) => (
                            <div
                                key={index}
                                className="flex items-center gap-4 bg-gray-50 dark:bg-black rounded-xl p-4 border border-gray-200 dark:border-gray-800 hover:border-emerald-500/50 dark:hover:border-emerald-500/50 transition-all duration-300 group"
                            >
                                <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center text-white group-hover:scale-110 transition-transform">
                                    {item.icon}
                                </div>
                                <p className="text-gray-700 dark:text-gray-300">
                                    {item.text}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Consent Section */}
                <div className="bg-gradient-to-br from-emerald-600 to-teal-700 rounded-2xl p-8 text-white shadow-xl">
                    <h2 className="text-2xl font-bold mb-4 flex items-center gap-3">
                        <CheckCircle className="w-7 h-7" />
                        Your Consent
                    </h2>
                    <p className="text-emerald-100 text-lg leading-relaxed">
                        By using our website, you hereby consent to our Privacy Policy and agree to its terms regarding the storage of your contact details and exam-related data.
                    </p>

                    {/* Contact */}
                    <div className="mt-6 pt-6 border-t border-white/20">
                        <p className="text-emerald-100 mb-4">For any privacy-related queries, contact us:</p>
                        <div className="flex flex-wrap gap-4">
                            <a
                                href="mailto:sheetal@profsheetalkunderacademy.com"
                                className="inline-flex items-center gap-2 bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-colors"
                            >
                                <Mail className="w-5 h-5 flex-shrink-0" />
                                <span className="text-sm sm:text-base break-all">sheetal@profsheetalkunderacademy.com</span>
                            </a>
                            <a
                                href="tel:+917400121111"
                                className="inline-flex items-center gap-2 bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg transition-colors"
                            >
                                <Phone className="w-5 h-5" />
                                <span>+91 7400121111</span>
                            </a>
                        </div>
                    </div>
                </div>

                {/* Footer Note */}
                <p className="text-center text-sm text-gray-500 dark:text-gray-500 mt-8">
                    Last updated: January 2026
                </p>
            </div>
        </div>
    );
}
